export interface opcion {
  texto: string,
  value: string
}

// Generated by https://quicktype.io

export interface PaisSmall {
  name: Name;
  cca2: string;
}

export interface Name {
  common: string;
  official: string;
  nativeName: NativeName;
}

export interface NativeName {
  spa: SPA;
}

export interface SPA {
  official: string;
  common: string;
}


// Generated by https://quicktype.io

export interface Pais {
  name: Name;
  tld?: string[];
  cca2: string;
  ccn3?: string;
  cca3: string;
  independent?: boolean;
  status: Status;
  unMember: boolean;
  currencies: Currencies;
  idd: Idd;
  capital: string[];
  altSpellings: string[];
  region: Region;
  subregion: Subregion;
  languages: { [key: string]: string };
  translations: { [key: string]: Translation };
  latlng: number[];
  landlocked: boolean;
  area: number;
  demonyms: Demonyms;
  flag: string;
  maps: Maps;
  population: number;
  car: Car;
  timezones: string[];
  continents: Region[];
  flags: CoatOfArms;
  coatOfArms: CoatOfArms;
  startOfWeek: StartOfWeek;
  capitalInfo: CapitalInfo;
  postalCode?: PostalCode;
  cioc?: string;
  borders?: string[];
  gini?: { [key: string]: number };
  fifa?: string;
}

export interface CapitalInfo {
  latlng: number[];
}

export interface Car {
  signs: string[];
  side: Side;
}

export enum Side {
  Left = "left",
  Right = "right",
}

export interface CoatOfArms {
  png?: string;
  svg?: string;
}

export enum Region {
  Europe = "Europe",
}

export interface Currencies {
  GBP?: TartuGecko;
  JEP?: TartuGecko;
  DKK?: TartuGecko;
  BGN?: TartuGecko;
  EUR?: TartuGecko;
  GIP?: TartuGecko;
  IMP?: TartuGecko;
  RSD?: TartuGecko;
  MDL?: TartuGecko;
  BAM?: BAM;
  NOK?: TartuGecko;
  FOK?: TartuGecko;
  CHF?: TartuGecko;
  UAH?: TartuGecko;
  CZK?: TartuGecko;
  RON?: TartuGecko;
  BYN?: TartuGecko;
  HRK?: TartuGecko;
  RUB?: TartuGecko;
  SEK?: TartuGecko;
  PLN?: TartuGecko;
  ALL?: TartuGecko;
  ISK?: TartuGecko;
  GGP?: TartuGecko;
  MKD?: TartuGecko;
  HUF?: TartuGecko;
}

export interface TartuGecko {
  name: string;
  symbol: string;
}

export interface BAM {
  name: string;
}

export interface Demonyms {
  eng: Eng;
  fra?: Eng;
}

export interface Eng {
  f: string;
  m: string;
}

export interface Idd {
  root: string;
  suffixes: string[];
}

export interface Maps {
  googleMaps: string;
  openStreetMaps: string;
}

export interface Name {
  common: string;
  official: string;
  nativeName: NativeName;
}

export interface Translation {
  official: string;
  common: string;
}

export interface PostalCode {
  format: string;
  regex: string;
}

export enum StartOfWeek {
  Monday = "monday",
}

export enum Status {
  OfficiallyAssigned = "officially-assigned",
  UserAssigned = "user-assigned",
}

export enum Subregion {
  CentralEurope = "Central Europe",
  EasternEurope = "Eastern Europe",
  NorthernEurope = "Northern Europe",
  SoutheastEurope = "Southeast Europe",
  SouthernEurope = "Southern Europe",
  WesternEurope = "Western Europe",
}
